// let text = "Please locate where 'locate' occurs!";
// let index = text.indexOf("locate");
// let text = "Please locate where your location";
// console.log(text.search("Please"));
// let text = "The rain in SPAIN stays mainly in the plain";
// text.match("ain");
// console.log(text.match("ain"));
let str = `Banhladesh`;
let sentence = `I love ${country} is big country`;
console.log("sentence");